# Generated by Django 3.2 on 2021-04-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='ram',
            field=models.CharField(max_length=250, verbose_name='RAM'),
        ),
    ]
