# Generated by Django 3.2 on 2021-05-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_notebook_ram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headphones',
            name='connection_type',
            field=models.CharField(choices=[('wire', 'By wire / MiniJack'), ('wireless', 'Wireless connection / Bluetooth')], default='wire', max_length=100, verbose_name='Headphones connection type'),
        ),
        migrations.AlterField(
            model_name='headphones',
            name='fastening',
            field=models.CharField(choices=[('earbuds', 'Ear buds'), ('vertical_bow', 'Vertical bow')], default='earbuds', max_length=100, verbose_name='Headphones fastening'),
        ),
        migrations.AlterField(
            model_name='smarttv',
            name='built_in_apps',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Built-in apps'),
        ),
        migrations.AlterField(
            model_name='smarttv',
            name='built_in_browser',
            field=models.BooleanField(default=False, verbose_name='Built-in browser'),
        ),
    ]
