# Generated by Django 3.2 on 2021-05-16 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210513_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='cart_fk',
            new_name='cart',
        ),
    ]
