# Generated by Django 3.2 on 2021-05-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_cart_fk_cartproduct_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='overall_price',
            new_name='final_price',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
